### ISSUE TITLE
Hardware object lost from the weak ref self.hardwareObjects

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#156]
Hi,

I observed a strange behavior in the HardwareRepository. Some hardware objects where initialized twice, which resulted that some channels where added also twice (in my case Attenuators). I put a print to see the content of `self.hardwareObjects` after each loading of a hwobj. And at some point the /attenuators object disappeared. Is there any reason why `hardwareObjects` could not be a dictionary?

https://github.com/mxcube/HardwareRepository/blob/f2a98e5f2022abeaf98b0de2c9ff4b36c4fb6ad9/HardwareRepository.py#L96

After replacing weakref with {} everything is fine.

**Comment by mguijarr** [comment]
Hi @IvarsKarpics,

The reason is : `self.hardwareObjects` is a cache of objects. In Python it is natural to have it as a weak container, to not retain object from being garbage-collected just because it is present in the cache.

It is the responsibility of the calling code to keep a (strong) ref of the objects returned by `.getHardwareObject`.

In the case you describe, I think the bug is more in the calling code somewhere a reference is not kept. Also, subscribing twice should not a problem because the first object is destroyed, obviously (since it is removed from the weakref dictionary) ? So this might be another bug in the calling code.

Replacing the weakref with a dict changes the intended behaviour of the code ; it will make all objects persistent along the life of the application. In the case of MXCuBE, it does not seem to be a problem since we do not load/unload hardware objects (except when using the UI editor ?).

In anyways, my comment is more for the record -- I hope hardware repository will soon disappear from MXCuBE codebase.

**Comment by IvarsKarpics** [comment]
Thanks @mguijarr  for the feedback. I had similar thoughts, but was surprised that the attached channel stayed even the hwobj disappeared from the weakref dictionary. Hmm, probably the hwobj was not destroyed fully with the garbage-collector.
Anyway, I do not think we need some actions here. I will close the issue.
