### ISSUE TITLE
from x import * 

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#320]
Hi,

There are still a few wildcard imports, notably in sample_changer but maybe also in other places. 

**Replace all remaining * imports by specific import statement(s)**

Marcus

**Comment by rhfogh** [comment]
I agree in principle. There might be one or two we could keep, because they cover a *lot* of variables and would be a lot of work to change:

-  'from Qt import *' in its various variants
- 'from queue_entry import *' (in SOLEILqueue_entry)

The SampleChange ones definitely need refactoring. 
There seems to be some with institution-specific mxcollects, like ESRFMultiCollect, and MAXLABMultiCollect, whcih I guess ought to be done, but we would need local input before making a final decision.

**Comment by marcus-oscarsson** [comment]
I see, first of all from Qt import * is quite ugly and should not be relevant for this repository.

I would really prefer if the * imports could be avoided everywhere but I'm not going to 
suggest that we force any site specific implementation to change it if its complicated.
