### ISSUE TITLE
get_beam_centre

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#341]
Looking through the code, some functions have get_beam_centre in e.g. AbstractCollect delegating to the detector_hwobj:
            return self.detector_hwobj.get_beam_centre()

But LimaEigerDetector, PilatusDetector and TacoMarDetector are delgating to the collect_hwobj:
 self.collect_obj.get_beam_centre()

Maybe this should be standardised and uput in either detector or collect always.

**Comment by rhfogh** [comment]
Another related point is that is seems that some get_beam_centre functions return values in pixels and others in mm.

**Comment by marcus-oscarsson** [comment]
Yes, this indeed needs to be harmonized. I'm not sure that get_beam_centre belongs to any of those objects but to Detector if any of those two. We simply just have to agree on the unit of the return value, pixels or mm is fine by me. I do have a slight preference for pixels since it would be slightly more accurate.
