### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#344]
Dear all,

We are not far away to have a python3 support (see: #343). From now it works on qt mockup version, but still it needs to be tested against site specific code. I created a new label python3 that should indicate issue related to python3 support.
For example I would use this issue to inform that method iteritems of a dict object do not exist in python3. So please have a look at your site specific code and do necessary changes.

**Comment by marcus-oscarsson** [comment]
Hi,

I said during last meeting that I would briefly mention what I'am using in the conversion process. There are still quite alot of print statements and imports of libraries that changed structures, such as urllib, StringIO, xmlrpc, http an so on left to be dealt with.

I basically run pylint --py3k and 2to3 tool to get an indication where I need to look. Please observer that we can't use the fixes suggested by 2to3 as they are because we also need to stay compatible with Python 2.7. Some of the suggestions are even sometimes not necessary like wrapping iterators in list.

There is also the possibility to run the python 2.7 interpreter with the -3 option to get warnings for Python 3 incompatible code.

My process basically consists of running 2to3 accepting only the changes I want with git, and the running  pylint --py3k to find the things I did not fix in the first pass.

Marcus

**Comment by IvarsKarpics** [comment]
I am closing the issue because the code is compatible with python3 and we run pytest via travis to check the compatibility.
