### ISSUE TITLE
BeamlineConfiguration object

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#368]
See issue #366 for preliminary discussions

I have some ideas for a BeamlineConfiguration object (nect comment), but it will require thinking and discussion, in part because we might have to change all the config files. I shall make a proper proposal, but it cannot be done in two days.

Meanwhile there are two options:
- make a provisional BeamlineConfiguration object using the code in Ivars 'api' for the content, pending agreement on a permanent solution
- Or continuing to use Ivars 'api' for now, bad though that is, until we have something better.

What do people prefer?

**Comment by rhfogh** [comment]
I think the BeamlineCOnfiguration object, and the associated config files, should have the following properties. Please comment:

- Singleton BeamlineConfiguration replaces both beamlinSetup and RepositoryClient
- Access from a top level module, like the HardwareRepositoryClient (getHardwareRepository())
- *All* access to HO inside MXCuBE is via role names
- The elements in config files are given as "<role>file.xml</role>" (e.g. "<collect>mxcollect.xml</collect>")
- The config file locations are *only* given inside beamline_configuration.xml
- Singleton objects (detector, collect) are direct attributes
- Multiple objects (shutters, motors) are dictionary attributes
-  BeamlineConfiguration use lazy loading - HardwareObjects are only loaded when accessed
- *All* object attributes in BeamlineConfiguration are coded explicitly as properties, so linters can see if the attribute exists
- You can add more objects at your beamline by subclassing (g.g.EMBLBeamlineConfiguration)
- Other hardware objects do NOT have 'object' elements with file.xml that are reae, but you can add local synonnyms, e.g. "<auto_centring>optical_auto_centring</auto_centring>")
- If there is no config file given for a role, the object is returned as None. There is no distinction between mandatory and optional roles; use testing code for that kind of thing.

**Comment by marcus-oscarsson** [comment]
- Singleton BeamlineConfiguration replaces both BeamlineSetup and RepositoryClient
  Ok

- Access from a top level module, like the HardwareRepositoryClient (getHardwareRepository())
  Ok, but maybe call the method something else

- *All* access to HO inside MXCuBE is via role names
  Of course

- The elements in config files are given as "\<role\>file.xml\</role\>" (e.g. "\<collect\>mxcollect.xml\</collect\>")
  Why not like its done now ?

- The config file locations are *only* given inside beamline_configuration.xml 
Ok

- Singleton objects (detector, collect) are direct attributes
Ok

- Multiple objects (shutters, motors) are dictionary attributes
Ok

- *All* roles supported in BeamlineConfiguration are coded explicitly as attributes (specifically properties), so linters can see if the corresponding attribute exists
Ok

-  BeamlineConfiguration uses lazy loading - HardwareObjects are only loaded when the attribute is accessed
I don't agree, I prefer that everything is loaded at start. Especially so that one can see if something goes wrong as early as possible

- You can add more roles at your beamline by subclassing (e.g. EMBLBeamlineConfiguration)
Ok

- Other hardware objects do NOT have 'object' elements with file.xml that are read, but you can add local role synonyms, e.g. "<auto_centring>optical_auto_centring</auto_centring>")
What do you mean by other hardware objects ?, im not sure that synonyms or aliases will make our lifes easier

- If there is no config file given for a role, the object is returned as None. There is no distinction between mandatory and optional roles; use testing code for that kind of thing.
All HardwareObjects on the Beamline object should in my opinion be mandatory if not defined differently. 

Testing sure, but a simple case that happens is that someone turns of something and don't realize until its to late. The application starts but something is not recorded because the equipment is turned off or in some error state, or were turning on and not ready when MXCuBE was started hence not initialized properly.

If not made mandatory one should at least have a summary of the equipment that were not initialized properly.

**Comment by IvarsKarpics** [comment]
Hi @marcus-oscarsson . Currently after loading the HardwareRepository there is a summary table with info about all hardware objects. Like:
```
+ ================================================================ +
| xml                      | Class                      | Load time|    
+ ================================================================ +
| /attenuators             | Attenuators                | 23 ms    |    
| /auto-processing         | EMBLAutoProcessing         | 6 ms     |    
| /beam-info               | BeamInfoMockup             | 61 ms    |    
| /beamline-setup          | BeamlineSetup              | 534 ms   |    
| /beamline-test           | EMBLBeamlineTest           | 10 ms    |  

```
I also think that it would be good to load everything once (like I do it now with api), so the gui can rely on the hwobjs.

**Comment by marcus-oscarsson** [comment]
Sure, that's nice but you don't see what did not load ...

**Comment by IvarsKarpics** [comment]
Yes, you see. For example I broke safety shutter xml and made a typo in ApertureMockup. So:

```
| /eh1/detector            | EMBLDetector               | 48 ms    |                  
| /eh1/detector-distance   | TINEMotor                  | 23 ms    |                  
| /eh1/diff-aperture       |                            | 0 ms     | Loading failed
| /safshut                 |                            | 2 ms     | Loading failed   
| /sc-generic              | SampleChangerMockup        | 5 ms     |                  
| /session                 | EMBLSession                | 9 ms     |   
```

**Comment by IvarsKarpics** [comment]
One can also add more info why the loading failed.

**Comment by marcus-oscarsson** [comment]
Ok, it was just missing in the first example then. That would be a minimum for me ...

**Comment by rhfogh** [comment]
- Lazy loading seems to be unpopular. I would propose making the individual attributes lazy-loading, and having a load_all or load_mandatory function that does
for role in role_list:
    getattr(self, role)
You would need the role_list anyway, to know what to load, and you can then call load_all right after initialising the object. That gives a bit more flexibility. BTW you should distinguish between 'Not configured', 'file not found', and 'error during loading'

- Changing from \<object\> to \<role\> would make it easier to avoid name duplication, and to see at a glance in the config what the roles are. But we can keep the current xml element structure if people prefer, as long as the internal dictionaries are all keyed by role.

- The idea is that all known hardwareobject  roles should be specified in the code of the BeamlineConfiguration class. I think it is good to put in the code (as properties) that there is such a thing as gphl_workflow or mesh_scan, or xray_centring, what the spelling is, and the (possibly abstract) class that the object must have. Then if you do not support either of those three you can just not put them in the configuration xml, and you will get None if you try to get hold of them. I think that is better than 1) having objects that are not shown in the code and lintable, 2) needing a special subclass if you wnat to support Gphl workflows.

- The point of synonyms is to take the place of the objects currently configured inside other HardwareObjects. Remember, you can no longer have e.g. "\<object href="/energy" role="energy"/\> inside e.g. mxcollect.xml - because all file locations must be only in beamline_configuration.xml. So I thought it might be useful to have e.g. 

    \<local_synonyms\>
        \<auto_centring\>xray_auto_centring\</auto_centring\>
    \</local_synonyms\>

That would allow you to configure Collect.auto_centring point to either xray_auto_centring of optical_auto_centring, while having ther relevant 
xml config files defined only in beamline_configuration.xml

But maybe there is no need for this?

- Another question is what other functions we might need. E.g. getDevices (if necessary) shouldbe here. Do we need unload and reload, to change config or hardwareobject while the program ie love?

**Comment by marcus-oscarsson** [comment]
@rhfogh 

I would probably call this object Beamline and not BeamlineConfiguration. I would also like to know how you see this object. I see it as way to provide a centralized point of access to objects and other functionality commonly used and in that way to define a common interface to access those ? This object can be partly or entirely implement the API used between the server and client. 

So that we can safely assume that energy is accessed through beamline.energy and exposes the AbstractEnergy interface on any MXCuBE installation. Is this how you see it ?

- Your reasoning around Lazy loading is unclear, I don't really understand what you would like to achieve with it. 

- I'm not sure we should change the xml syntax, maybe extend it but not change it to drastically. There might be a need for it, but I think we should focus on the Beamline object for now.

- I agree that making some objects "optional" is definitely necessary

- As I said above, I do think is good if we can refactor parts of the Hardware Repository so that one for instance don't need to add references to already referenced HardwareObjects. I'm however not sure that we should focus on that directly. I further don't see how synonyms would be help full, I imagine that we can access the Beamline object from any HardwareObject ?

**Comment by rhfogh** [comment]
- *" I see it as way to provide a centralized point of access to objects and other functionality commonly used and in that way to define a common interface to access those "* So do I.
- *"I would probably call this object Beamline"* - Will do.
- *I'm not sure we should change the xml syntax, "* Fine with me.
- "*I further don't see how synonyms would be help full"*. Excellent. I would rather not code them if I do not have to.
- Personally I would say that as long as we still allow referencing HardwareObjects from other HardwareObjects, using 'getHardwareObject("filename.xml")' , we have achieved neither the clarity, nor the reliabllity, nor the robustness, that we want with this change. But by all means let us move into it gradually.

Anyway, I now understand better what we need to achieve. I think the next step will be for me to make a properly coded WIP for people to discuss and react to. Which will take some days.

**Comment by marcus-oscarsson** [comment]
Done
