### ISSUE TITLE
Create AbstractResolution

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#450]
Create and AbstractResolution derived from AbstractMotor

**Comment by marcus-oscarsson** [comment]
We should maybe consider this just as we have AbstractTransmission, but the ineheritance should be from AbstractActuator and not AbstractMotor

**Comment by rhfogh** [comment]
What is teh argument ofr using  AbstractActuator instead of AbstractMotor?

**Comment by marcus-oscarsson** [comment]
Hm, no you are right that using AbstractMotor would actually not be a problem

**Comment by rhfogh** [comment]
Sorry to be off topic, but since this one is still open,:
Many thanks, @marcus-oscarsson for your timely and effective issues clean-up.

**Comment by beteva** [comment]
@rhfogh, @marcus-oscarsson I was lookint at the issue yesterday and wanted to wait to discuss about it during the wrap-up, but we can do this now as well. I am not completely sure that we need AbstractResolution after all.  Maybe just a frame the same way as AbstractTransmission, because it combines some parameters from the detector and the energy and we can provide some "standard" calculations. The question I am not sure about is how "standard" this calculations are - maybe you @rhfogh and @MartinSavko could answer. As for the inheritance, in my opinion it should be AbstractMotor, because of the update_value and validate_value implementation.

**Comment by rhfogh** [comment]
@beteva 
I would suggest that we could probably write a single universal Resolution class that could be used everywhere. In that sense we would not need an AbstractResolution. 

Resolution is basically a wrapper around the detector distance and the energy. Looking at the functions currently in Resolution (which should be a good start):

- get_beam_centre could be removed, and the detector.get_beam_position could be used instead. 
- resolution_to_distance and get_value_at_corner could be rewritten to get rid of the 'ax','by' etc. stuff (that is indeed beamline-specific) and instead call detector.get_radius, and a new function called detector.get_distance_to_corner, or maybe better get_outer_radius. 
- All the other functions could stay pretty much as they are, calling functions on the detector or energy to do what they need.

What say you?

**Comment by beteva** [comment]
@rhfogh, this goes in the direction I was taking as well, including your comments.

**Comment by marcus-oscarsson** [comment]
That sounds good to me
