### ISSUE TITLE
[Dicussion] AbstractNState to be renamed to AbstractNPosition 

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#451]
Discussion about AbstractNState

- Define limited set of states available within MXCuBE 
- Map all states to one of the predefined states
- Distinguish between the defined state and devices actual state

**Comment by jordiandreu** [comment]
Let me start by writing down the ideas we discussed in the virtual f2f meeting:

**What I understand for State Machine concept:**
We usually request the state of a HardwareObject when we want to know if a certain operation involving the HwObj can be done safely. For this, a simple method like is_ready could suffice, just returning the READY/NOT_READY (or whatever binary state we could define). For some hardware, a more detailed list of states can help to decide how to proceed in more detail. For instance, the current list of motor states is an example of a detailed states list that any given motor could report. If a given motor returns LIM+ means the motor cannot be moved to the positive direction, but (is ready) to the negative one.

**Discrete positions/states**
In the other hand, we have some equipment which could have several discrete positions (= configurations = states) like a shutter (open/close), a light (on/off), or a discrete zoom (with N different values). These position (or state) values are the main attribute of the hardware (as we did decide to be the position for a motor).

Then, one proposal could be:

1. Implement the concept of state machine low HardwareObject level and inherit by HardwareObject classes. The States here could be (a) A fixed list (enum) of states shared for all hardware objects or (b) Each hardware object could have its own list of states (maybe some lists shared among different HwObjs).

1. In the other hand, elements like the shutters, lights, etc, would be examples of equipment type candidate to be implemented as an AbstractActuator or AbstractNState class. In this case, the discrete position (or state) will be specific for each hardware. However, a basic set of states could be defined in the base class as well (ON/OFF, OPEN/CLOSE, etc...).

**Comment by rhfogh** [comment]
@jordiandreu 
I agree with you, but I would cut the cake slightly differently. AFAIAC, all hardware objects should support the following five states, which together4 comprose the state machine:

READY, BUSY, WAITING, FAULT, UNKNOWN.

Of these, BUSY means the HO is doing something and will become READY when it has finished; WAITING means that it is idle but not ready, because it is waiting for something else (initialisation to finish, the detector cover to be removed, ...). 

I think there should be a function (I prefer one, but a group of functions would do), that for any HardwareObject will return one of those five states.

Other states, LIMPOS, LIMNEG, HOME, LOADING, ALARM, DIASABLED, CHARGING, ...) are specific to particluar (kinds of) HardwareObject, and should be returned by a separate function. I think that the two kinds of states shoudl NOT be mixed, so that a given call returns either one or the other. 

A third kind of state, conceptually, are the values for NState objects, like IN/OUT, OPeee

**Comment by marcus-oscarsson** [comment]
Decision was finally to introduce AbstractActuator and keep AbstractNState (inheriting AbstractActuator)
