### ISSUE TITLE
Use AbstractActuator for AbstractTransmission

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#459]
Use AbstractActuator (when it becomes available) for AbstractTransmission

**Comment by jordiandreu** [comment]
In my opinion, I think we should avoid the inheritance of specific abstract classes and only inherit from HardwareObject class. Let me  explain.

In the real world, you can have many different mechanical designs for your instrumentation. For instance, you can have a motor which moves some foils or use a set of valves (actuators) that combine different foils to match the requested transmission. The AbstractTransmission class should provide an API (public attributes and methods) to guarantee the correct operation and monitor of the transmission independent of the mechanical implementation behind. If we inherit from another abstract  class, we are also exposing its API. In other words, if we use an actuator or a motor to control the transmission, should be hidden behind the transmission API i.e. the application should be agnostic of the mechanical implementation.

**Comment by jordiandreu** [comment]
@marcus-oscarsson , maybe this should be discussed before the code camp?

**Comment by rhfogh** [comment]
@jordiandreu, @marcus-oscarsson 
I am not sure I agree with, Jordi. I think we are mixing two issues here, the mechanical implementation and the software signature. 

From a coding point of view, an AbstractActuator is anything that has a value that can be set as a continuous floating point variable, no matter how the hardware is implemented. It does not matter if it picks the nearest of a set of fixed values, just that it is set and got as a free float. Similarly an AbstractNState is anything that is set by selecting from a set of predefined values. If we want something that can do both we would need a separate abstract class to do that. 

If we are to allow non-beamline-specific coding (which I devoutly hope we can) we have to decide whether a Transmission is set by passing in a float or selecting from a list of possibilities (or both). And once we have done that, I think we can and should use the appropriate abstract class, in order to guarantee uniformity and reduce code duplication. AFAIAC the more we can code at abstract level,the better.

If there is a special problem with transmission, we can discuss that But I would really regret trying to get rid of the various abstract classes altogether. Is that what you are suggesting?

**Comment by marcus-oscarsson** [comment]
@ALL, 

Hm, yes. We do indeed need to discuss this before the code camp so that we are on the same page. The idea is as @rhfogh says that we with the abstract classes want to define the minimum common functionality for the equipment were that functionality is applicable. This is, as you already know, usually equipment that performs the same or similar tasks but in different ways.

The abstract classes, as you also already know, allows us to know what to expect in terms of data that is exchanged and the minimum functionality we can expect, basically the minimum common API for the equipment.

I think this is quite important for several reasons:

- It makes it easier to use MXCuBE (HWR) across beamlines with different hardware setups, as we have a "contract" the defines how to interact with the hardware. 

- Makes it easier to develop the MXCuBE UI and other applications built on top of HWR 

- Makes it easier to understand HWR as the abstract classes to some extent are self documenting

I would say that its mainly for these three reasons that I could summarize as portability that I think the abstract classes are important.

I'm not sure I understand your message above completely because I think you agree to all of these points :). Do you mean that we should keep the abstract classes but not just inherit from at all or just in some cases ?

Marcus

**Comment by beteva** [comment]
Hi @ALL,
i do agree with @marcus-oscarsson, **having the abstract classes allows us to have very clear API, which is after all why we have started all this huge refactoring of the Hardware Repository.**
@jordiandreu , we could say that most of the Abstract classes should inherit from BaseHardwareObject, but this should not be a golden rule. Already we have AbstractNState and AbstractMotor, that inherit from AbstractActuator and as out test show, it is quite convenient and clear structure (well argumented by @rfogh above). There is one point you are right - we should not mix hardware implementation and abstract class methods, but this is not because of inheriting of the another abstract class.
As a conclusion, I think we are on a stage to confirm the list of abstract classes on which we've already been agreed on last developers meeting and well document them during the next meeting.

**Comment by jordiandreu** [comment]
Hi @ALL,
I agree with all of you so, probably i did not express my idea clearly enough :)
* My comment was only related to the AbstractTransmission class.
* We use abstract classes to inherit from, of course!

When we derive the AbstractMotor class from AbstractActuator, we are extending the AbstractActuator API with some additional attributes related to what a motor is: velocity, homing, etc...If we derive the AbstractTransmission from AbstractActuator, what will be the new attributes which define the AbtractTransmission class?

My point is that maybe we do not need a class for AbstractTransmission. Maybe and we can implement it as a Motor or as an Actuator, keeping the implementation more flexible than forcing to inherit from AbstractActuator...nevertheless, I'm in favor of as much AbstractClasses as necessary!

**Comment by marcus-oscarsson** [comment]
:), that's what I thought. It makes it much clearer. So basically is it enough that transmission is modeled as AbstractActuator/NState or do we actually need something called AbstractTransmission ?It seems to me like AbstractActuator would be sufficient, what do you think @beteva

**Comment by beteva** [comment]
Well, not a clear opinion, only a feeling.
I feel like we need the AbstractTransmission, as it is needed at the same line as the energy. By inheriting from AbstractActuator and not from HardwareObject we use the get/set_value, limits and update methods. in addition we can implement the dependency on the energy. The differences in the hardware will be implemented in each specific _set_value and maybe (not sure though) we can introduce calculate_transmission method.

**Comment by marcus-oscarsson** [comment]
@ALL, I think we can close this one, please reopen if you think its sill relevant
