### ISSUE TITLE
state and specific_state handling - particularely for BlissMotor

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#537]
@beteva, @natxo14 
I had somecomments on the just accepted BlissMotor PR #533, but I saw afterwards that it is anyway planned to refactor it in a new PR, so I have removed them again. Please disregard the previous version.. Sorry for being inattentive.

**Comment by natxo14** [comment]
Hi Rasmus!

No need to apologise, feedback it's always welcome :) . 
I hope if you don't mind if I put the message you left on the PR, I think it can help to track the issues you found in BlissMotor:

"
The changes to BlissMotor state handling in the recently accepted #533 PR raises some questions.
Specifically, the behavlour of the update_state function seems to be inconsistent with the documentation; which suggests that one or the other maybe ought to be changed.

    The documentation to HardwareObjectMixin.get_state gives the wrong type for the result. This is my fault, a hangover from an old proposal, AFAIAC the documentation ought to be changed to to match that for HardwareObjectMixin.update_state. But since neither documentation matches the current BlissMotor code we had better make a single, concerted set of changes.

    The documentation for BlissMotor.update_state says that the input must be a HardwareObjectState (as indeed required by the superclass function that is being overridden). But the code shows that the input can in practice also be a boolean or a state returned from the BlissMotor

    specific_state is sometimes set to a HardwareObjectState, not a BlissMotorState (line 109). If we want to do that it really ought to be reflected in th documentation, also in the superclass. Also it should be clarified whether the specific state for a given class should return the BlissMotorState or the HardwareObjectState for READY and UNKNOWN, a mixture, or any state with the right name.

If we want to keep to the superclass documentation, we could rewrite the functions to suit. Most obviously we could connect the Motor to a _update_state function, that in turn called update_state with a parameter of the correct type. Alternatively we would decide that the superclass documentation does not reflect what we want, and rewrite the superclasses so that they show the desired implementation.
"
Thanks a lot

**Comment by beteva** [comment]
@rfogh, I am currently working on BlissMotor in order to change the update_state to a local _updte_state method, which only translates the BLISS states to HardwareObjectStates The PR will follow today.

**Comment by rhfogh** [comment]
@beteva Sounds good. Pity I had not noticed your comment it two minutes earlier.

**Comment by marcus-oscarsson** [comment]
@beteva great ! and thanks @natxo14 for the very detailed and thorough feedback :)

**Comment by marcus-oscarsson** [comment]
@beteva, done right ?

**Comment by beteva** [comment]
Yes, this has been closed by #540
