### ISSUE TITLE
Hardware Object specific states

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/HardwareRepository#555]
Regarding the definition, usage and implementation of the SPECIFIC_STATES for Hardware Objects:

We are in a scenario in which different HwObj might have different STATES. We decided to reduce the number of those STATES to a limited list defined at the BaseHardwareObject level:

    UNKNOWN = 0
    WARNING = 1
    BUSY = 2
    READY = 3
    FAULT = 4
    OFF = 5

In practice, this means that any implementation of a HardwareObject class must map the set of states for a given hardware or abstraction to the Hardware Object STATES. Thus, MXCuBE must only use these STATES for the application logic i. e. if we need to check if a motor can be moved or actuate a shutter.

Nevertheless, this mapping between the internal hardware states and the HardwareObject STATES is an information reduction process. In some situations, seems that getting some more details about the hardware state can be interesting.

The question then is how can we provide this info?

The current implementation defines an extra attribute called SPECIFIC_STATES which in my opinion has some weak points:

1. Duplication of the STATES now for SPECIFIC_STATES code: methods, signals, etc...
2. Application logic must be only based on STATES and never use SPECIFIC_STATES since the depend on specific hardware
3. ...

To overcome these, I could envisage some alternatives:

1. Provide some extra states, specific to each Hardware Object (SPECIFIC_STATES). This can be probably implemented in different ways:
    1. Extend the list of STATES for some HardwareObjects: For instance, for an AbstractMotor class we could update the set of STATES with a specific set of SPECIFIC_STATES for a motor. Here I think we will need to cope with this list of extended states in the application logic.

    1. Complement the list of STATES: For instance, STATE could be a tuple Motor_State = (STATUS, SPECIFIC_STATE).
    
2. Specific method in the API: on_pos_limit? on_negative_limit? at_home?

Probably, some other approaches can exists. What I propose is to complete these approches if someone has more ideas and discuss about their PROS and CONS.

**Comment by rhfogh** [comment]
@jordiandreu 
Unfortunately your alterntaives also have problems - there is no easy solution to this one. Some comments:

1. i If you extend the list of states returned by get_state, your application will need to deal with all the unknown extra states. That cannot be done in  a general way, exactly because the extra states are unknown and locale-specific. How can I know whether a motor in state HIGHLIMIT or MOVING or AUTO is ready or not, unlesss I konw exactly how that motor is implemented? Going in this direction loses the advantage of having a shared and general set of states.

1. ii Returning a tuple of (general, specific) states is no different in principle from returning them separately - you still have the problems that come from defining two separate and partially overlapping sets of states. It is just a more complicated implementation, since you need to get a tuple and unwrap the atttribute you are interested in, even when you only want one of them. Sure, you need to define one less signal; in return you need to pass a specific state and disambiguate the tuple even in the common case where there are no specific states at all.
 
2. Having separate functions is again another way to implement a separate set of states. Seeing that there will then be no top-level agreed machinery at all, it seems equivalent to saying that specific_sites are unregulated and eveybody can implement them in their own way. Since I will never use specific states for anything I have no objection personally. I will say that if you have a set of several mutually exclusive states (like HOME, HIGH_LIMIT, LOW_LIMIT, and MOVING), having individual functions seeems a bit wasteful, but in coding them all, and in checking them one by one. If we want to save on signals I gues we could remove the specifcStateChanged signal, and simply have people call get_specific_state expliticly when they needed it. After all, the specific state will only change when hte gneral state, or the value, or boht also change.

I still think that the least bad option is to have state and specific_state separate. State is then clear, well-defined, and the same everywhere. Specific_state needs only be implemented and considered in those specific cases where someone needs it for something, and then they are totally free to handle in in whatever way suits them best without caring about conforming to other people's preferences.

**Comment by beteva** [comment]
I also agree that separating the state and the specific states provides quite a reasonable equilibrium between a well defined, with a limited number of values STATES, which is easy to handle for both QT and WEB  front end and a more detailed, but possibly quite specific SPECIFIC_STATES. I see the SPECIFIC_STATES as giving extra details, only on demand, which may not even need a signal emit. On the other hand, the STATES list should stay short and immutable, in order to allow a clear API for any application.

**Comment by marcus-oscarsson** [comment]
I'm considering this discussion resolved, but please feel free to reopen if there is still an on going/unsettled discussion
