### ISSUE TITLE
ispyb client

### ISSUE THREAD

**Issue by 13bscsaamjad** [mxcube/HardwareRepository#571]
Why is the key "remoteEnergy" deleted [here](https://github.com/mxcube/HardwareRepository/blob/master/HardwareObjects/ISPyBClient.py#L1478)?

**Comment by marcus-oscarsson** [comment]
Hi Abdullah,

The only good reason I think of is that this fields was maybe removed (or renamed) from the database table and passing it to the WS somehow caused a problem. But I have to admit that I'm not certain, but it looks like a possibility. Its otherwise hard to explain ;)

@beteva, @IvarsKarpics any other ideas ?

All the best,
Marcus

**Comment by IvarsKarpics** [comment]
There is a related PR in ispyb: https://github.com/ispyb/ISPyB/pull/491

**Comment by marcus-oscarsson** [comment]
So the column was removed and now being put back again, see link above.
